repo:
  - ./*

climate-change:
  - any: ['_hackbars/*.md', 'assets/images/*']
  
hackbar:
  - all: ['_hackbars/*.md', 'assets/images/*']
  
python:
  - python/*.py
  
javascript:
  - javascript/*.js
  
cpp:
  - cpp/*.cpp
  
documentation:
  - README.md
