repo:
  - ./*

climate-change:
  - _hackbars/*.md
  
hackbar:
  - _hackbars/*.md
  - assets/images/**
  
python:
  - python/*.py
  
javascript:
  - javascript/*.js
  
cpp:
  - cpp/*.cpp
  
documentation:
  - README.md
