# This is a basic workflow to help you get started with Actions

name: Check Hackbar

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  file_existance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files:  "*.md, *.jpg"
      
      - name: File not exists
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
      
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!

